apiVersion: tekton.dev/v1
kind: Pipeline
metadata:
  name: build-pipeline
spec:
  tasks:
  - name: origin
    taskSpec:
      steps:
      - name: start
        image: quay.io/konflux-ci/tools@sha256:a42cfa49ba1adff89d940538b89adbcc765e83f1adffe841775ecf27f657058b
        script: |
          echo start origin
  - name: init
    taskRef:
      params:
      - name: name
        value: init
      - name: bundle
        value: quay.io/konflux-ci/tekton-catalog/task-init:0.2@sha256:2f59e9a3c20ce4509356389d327087213cc82c079b30811935837791da140f9f
      - name: kind
        value: task
      resolver: bundles
  - name: clone
    taskRef:
      params:
      - name: name
        value: git-clone-oci-ta
      - name: bundle
        value: quay.io/konflux-ci/tekton-catalog/task-git-clone-oci-ta:0.1@sha256:3e171c1f3a9487a5764ebef629f93b3d2fc01cc8bad382dd8065cdfe42214148
      - name: kind
        value: task
      resolver: bundles
    workspaces:
    - name: source
      workspace: workspace
  - name: build-container
    taskRef:
      params:
      - name: name
        value: buildah
      - name: bundle
        value: quay.io/konflux-ci/tekton-catalog/task-buildah:0.4@sha256:90192492079667e2f88c5a41760c6a16f168bfcd5d32c8e053268789960fcf5f
      - name: kind
        value: task
      resolver: bundles
    workspaces:
    - name: source
      workspace: workspace
    runAfter:
    - clone
  - name: build-source-image
    taskRef:
      params:
      - name: name
        value: source-build
      - name: bundle
        value: quay.io/konflux-ci/tekton-catalog/task-source-build:0.3@sha256:9e567501dd67e30b1dd1d16f859c767323f762335bad7a1ad4107deca2e2c9a7
      - name: kind
        value: task
      resolver: bundles
    workspaces:
    - name: source
      workspace: workspace
    runAfter:
    - build-container
  workspaces:
  - name: workspace
